name: sudoku_poc
description: A completely free, offline-capable Sudoku game.
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  intl: ^0.19.0 # For timer formatting
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_async: ^1.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  assets:
    - assets/puzzles/
    - assets/icon/
    - assets/splash/

  uses-material-design: true
